import json
import os
import sys


# ─── ANSI colour helpers ──────────────────────────────────────────────────────

def _use_color() -> bool:
    """Return True when stdout is a TTY and NO_COLOR is not set."""
    return sys.stdout.isatty() and os.environ.get("NO_COLOR", "") == ""


_RESET  = "\033[0m"
_BOLD   = "\033[1m"
_RED    = "\033[91m"
_YELLOW = "\033[93m"
_GREEN  = "\033[92m"
_CYAN   = "\033[96m"
_DIM    = "\033[2m"


def _c(text: str, *codes: str) -> str:
    """Wrap *text* with ANSI codes only when color is enabled."""
    if not _use_color():
        return text
    return "".join(codes) + text + _RESET


# ─── HTML template ────────────────────────────────────────────────────────────

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>ArduPilot Log Diagnosis — {filename}</title>
<style>
  body{{font-family:system-ui,sans-serif;max-width:860px;margin:2rem auto;padding:0 1rem;color:#1a1a2e;background:#f4f6f9}}
  h1{{font-size:1.4rem;margin-bottom:.25rem}}
  .meta{{color:#555;font-size:.85rem;margin-bottom:1.5rem}}
  .badge{{display:inline-block;padding:.25rem .7rem;border-radius:999px;font-weight:700;font-size:.8rem;margin-right:.4rem}}
  .critical{{background:#fde8e8;color:#c0392b}}
  .warning{{background:#fef9e7;color:#d35400}}
  .info{{background:#e8f6fd;color:#2471a3}}
  .healthy{{background:#e9f7ef;color:#1e8449}}
  .card{{background:#fff;border-radius:8px;box-shadow:0 1px 4px rgba(0,0,0,.1);padding:1.2rem 1.5rem;margin-bottom:1rem}}
  .card h2{{margin:0 0 .5rem;font-size:1rem}}
  .evidence{{background:#f8f9fa;border-left:3px solid #aaa;padding:.4rem .8rem;margin:.5rem 0;font-family:monospace;font-size:.85rem}}
  .fix{{margin-top:.5rem;font-size:.9rem;color:#333}}
  .subsystem-table{{width:100%;border-collapse:collapse;font-size:.88rem}}
  .subsystem-table td,.subsystem-table th{{padding:.35rem .6rem;border-bottom:1px solid #eee;text-align:left}}
  .bar{{display:inline-block;height:10px;border-radius:3px;background:#3498db;vertical-align:middle}}
  .similar-case{{border-left:3px solid #3498db;padding:.4rem .8rem;margin:.4rem 0;font-size:.88rem}}
  footer{{color:#aaa;font-size:.75rem;text-align:center;margin-top:2rem}}
</style>
</head>
<body>
<h1>🚁 ArduPilot Log Diagnosis Report</h1>
<div class="meta">
  <strong>Log:</strong> {filename} &nbsp;·&nbsp;
  <strong>Duration:</strong> {duration} &nbsp;·&nbsp;
  <strong>Vehicle:</strong> {vehicle}
</div>
{body}
<footer>Generated by <a href="https://github.com/BeastAyyG/ardupilot-log-diagnosis">ardupilot-log-diagnosis</a></footer>
</body>
</html>
"""


class DiagnosisFormatter:
    """Formats diagnosis output for humans."""

    # ------------------------------------------------------------------
    # Terminal (ANSI-coloured when stdout is a TTY)
    # ------------------------------------------------------------------

    def format_terminal(
        self, diagnoses: list, metadata: dict, decision: dict = None,
        similar_cases: list = None
    ) -> str:
        lines = []
        lines.append(_c("╔═══════════════════════════════════════╗", _BOLD))
        lines.append(_c("║  ArduPilot Log Diagnosis Report       ║", _BOLD))
        lines.append(_c("╠═══════════════════════════════════════╣", _BOLD))
        filename = metadata.get("log_file", "unknown").split("/")[-1]
        lines.append(_c(f"║  Log:      {filename:<27}║", _BOLD))
        duration = metadata.get("duration_sec", 0.0)
        mins = int(duration // 60)
        secs = int(duration % 60)
        dur_str = f"{mins}m {secs}s"
        lines.append(_c(f"║  Duration: {dur_str:<27}║", _BOLD))
        vehicle = (
            f"{metadata.get('vehicle_type', 'Unknown')} {metadata.get('firmware', '')}"
        )
        lines.append(_c(f"║  Vehicle:  {vehicle:<27}║", _BOLD))
        lines.append(_c("╚═══════════════════════════════════════╝", _BOLD))
        lines.append("")

        # Abstain / uncertain state — show this before diagnosis loop
        if decision and decision.get("status") == "uncertain" and not diagnoses:
            lines.append(_c("UNCERTAIN — HUMAN REVIEW REQUIRED", _YELLOW, _BOLD))
            lines.append("  Confidence below threshold on all candidates.")
            for r in decision.get("rationale", []):
                lines.append(f"  · {r}")
            lines.append("")
            lines.append(_c("Overall: SEND TO EXPERT", _YELLOW, _BOLD))
            return "\n".join(lines)

        if not diagnoses:
            lines.append(_c("✔  HEALTHY — No critical failures detected.", _GREEN, _BOLD))
            if decision:
                lines.append(f"Decision: {decision.get('status', 'healthy').upper()}")
            lines.append("")
            lines.append(_c("Overall: SAFE TO FLY ✔", _GREEN, _BOLD))
            return "\n".join(lines)

        overall_safe = True

        for d in diagnoses:
            ftype = d["failure_type"].upper()
            pct = int(d["confidence"] * 100)
            sev = d["severity"].upper()
            if sev == "CRITICAL":
                overall_safe = False
                sev_str = _c(f"{sev} — {ftype} ({pct}%)", _RED, _BOLD)
            elif sev == "WARNING":
                sev_str = _c(f"{sev} — {ftype} ({pct}%)", _YELLOW, _BOLD)
            else:
                sev_str = _c(f"{sev} — {ftype} ({pct}%)", _CYAN, _BOLD)

            lines.append(sev_str)
            for ev in d.get("evidence", []):
                feature = ev.get("feature")
                val = ev.get("value")
                thresh = ev.get("threshold")
                lines.append(_c(f"  {feature} = {val} (limit: {thresh})", _DIM))
            lines.append(f"  Method: {d['detection_method']}")
            lines.append(_c(f"  ➜ Fix: {d['recommendation']}", _CYAN))
            lines.append("")

        if overall_safe:
            lines.append(_c("Overall: PROCEED WITH CAUTION ⚠", _YELLOW, _BOLD))
        else:
            lines.append(_c("Overall: NOT SAFE TO FLY ✘", _RED, _BOLD))

        if decision:
            lines.append("")
            lines.append(f"Decision: {decision.get('status', 'unknown').upper()}")
            top_guess = decision.get("top_guess")
            top_conf = int(float(decision.get("top_confidence", 0.0)) * 100)
            if top_guess:
                lines.append(f"Top Guess: {top_guess.upper()} ({top_conf}%)")

            subsystems = decision.get("ranked_subsystems", [])
            if subsystems:
                lines.append("\nSubsystem Blame Ranking:")
                for sub in subsystems[:3]:  # top 3
                    lines.append(
                        f"  - {sub['subsystem']:>18}: {int(sub['likelihood'] * 100)}%"
                    )

            if decision.get("requires_human_review"):
                lines.append(_c("\n⚠  Human Review: REQUIRED", _YELLOW, _BOLD))
                for r in decision.get("rationale", []):
                    lines.append(f"   · {r}")
            else:
                lines.append(_c("\nHuman Review: Not required ✔", _GREEN))

        if similar_cases:
            lines.append("\nSimilar Historical Cases:")
            for case in similar_cases:
                pct = int(case["similarity"] * 100)
                lines.append(f"  [{pct}%] {case['failure_type']}")
                if case.get("root_cause"):
                    lines.append(f"         Cause: {case['root_cause']}")
                if case.get("fix"):
                    lines.append(f"         Fix:   {case['fix']}")
                if case.get("source_url"):
                    lines.append(f"         Ref:   {case['source_url']}")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # JSON
    # ------------------------------------------------------------------

    def format_json(
        self, diagnoses: list, metadata: dict, features: dict, decision: dict = None,
        similar_cases: list = None
    ) -> str:
        return json.dumps(
            {
                "metadata": metadata,
                "diagnoses": diagnoses,
                "decision": decision or {},
                "similar_cases": similar_cases or [],
                "features_summary": {
                    k: v for k, v in features.items() if not k.startswith("_")
                },
            },
            indent=2,
        )

    # ------------------------------------------------------------------
    # HTML
    # ------------------------------------------------------------------

    def format_html(
        self, diagnoses: list, metadata: dict, features: dict,
        decision: dict = None, similar_cases: list = None
    ) -> str:
        filename = metadata.get("log_file", "unknown").split("/")[-1]
        duration = metadata.get("duration_sec", 0.0)
        mins = int(duration // 60)
        secs = int(duration % 60)
        dur_str = f"{mins}m {secs}s"
        vehicle = (
            f"{metadata.get('vehicle_type', 'Unknown')} "
            f"{metadata.get('firmware', '')}".strip()
        )

        if not diagnoses:
            body = (
                '<div class="card">'
                '<span class="badge healthy">✔ HEALTHY</span>'
                ' No critical failures detected. Safe to fly.'
                "</div>"
            )
        else:
            cards = []
            for d in diagnoses:
                sev = d["severity"].lower()
                ftype = d["failure_type"].replace("_", " ").title()
                pct = int(d["confidence"] * 100)
                badge = f'<span class="badge {sev}">{sev.upper()} {pct}%</span>'
                ev_html = "".join(
                    f'<div class="evidence">{ev.get("feature")} = '
                    f'{ev.get("value")} &nbsp;(limit: {ev.get("threshold")})</div>'
                    for ev in d.get("evidence", [])
                )
                fix = d.get("recommendation", "")
                method = d.get("detection_method", "")
                cards.append(
                    f'<div class="card">'
                    f"<h2>{badge} {ftype}</h2>"
                    f"{ev_html}"
                    f'<div class="fix">🔧 {fix}</div>'
                    f'<div style="margin-top:.4rem;font-size:.8rem;color:#888">Method: {method}</div>'
                    f"</div>"
                )

            overall = decision.get("status", "unknown").upper() if decision else "UNKNOWN"
            safe_html = (
                '<span class="badge healthy">✔ SAFE</span>'
                if overall == "HEALTHY"
                else (
                    '<span class="badge critical">✘ NOT SAFE TO FLY</span>'
                    if overall == "CONFIRMED"
                    else '<span class="badge warning">⚠ PROCEED WITH CAUTION</span>'
                )
            )

            subsystem_rows = ""
            if decision:
                for sub in (decision.get("ranked_subsystems") or [])[:5]:
                    pct = int(sub["likelihood"] * 100)
                    bar = f'<span class="bar" style="width:{pct * 2}px"></span>'
                    subsystem_rows += (
                        f"<tr><td>{sub['subsystem']}</td>"
                        f"<td>{bar} {pct}%</td></tr>"
                    )

            subsystem_section = ""
            if subsystem_rows:
                subsystem_section = (
                    '<div class="card"><h2>Subsystem Blame Ranking</h2>'
                    '<table class="subsystem-table"><tr><th>Subsystem</th><th>Likelihood</th></tr>'
                    f"{subsystem_rows}</table></div>"
                )

            similar_section = ""
            if similar_cases:
                items = "".join(
                    f'<div class="similar-case">'
                    f'<strong>[{int(c["similarity"] * 100)}%]</strong> '
                    f'{c["failure_type"].replace("_", " ").title()}'
                    + (f' — {c["fix"]}' if c.get("fix") else "")
                    + (
                        f' <a href="{c["source_url"]}" target="_blank" style="font-size:.8rem">ref</a>'
                        if c.get("source_url")
                        else ""
                    )
                    + "</div>"
                    for c in similar_cases
                )
                similar_section = (
                    f'<div class="card"><h2>Similar Historical Cases</h2>{items}</div>'
                )

            body = (
                "".join(cards)
                + f'<div class="card"><strong>Overall:</strong> {safe_html}</div>'
                + subsystem_section
                + similar_section
            )

        return _HTML_TEMPLATE.format(
            filename=filename,
            duration=dur_str,
            vehicle=vehicle,
            body=body,
        )
