"""Validate, plan, or execute controlled ArduPilot SITL scenarios.

This command never fabricates placeholder `.BIN` files. Execution requires an
already-running, armed ArduPilot SITL vehicle and a MAVLink connection.

Examples:
    python training/sitl_data_factory.py --validate
    python training/sitl_data_factory.py --list
    python training/sitl_data_factory.py --scenario gps_loss
    python training/sitl_data_factory.py --scenario gps_loss --execute \
        --connect tcp:127.0.0.1:5760 --output-dir data/sitl_runs
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import asdict
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from src.simulation.scenario_runner import (
    MavlinkSITLTransport,
    SITLScenarioRunner,
    load_scenarios,
)


DEFAULT_MANIFEST = (
    ROOT_DIR
    / "simulation"
    / "sitl_scenarios.yaml"
)


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Validated ArduPilot SITL fault-scenario runner"
    )
    parser.add_argument(
        "--manifest",
        default=str(DEFAULT_MANIFEST),
        help="Scenario YAML manifest",
    )
    action = parser.add_mutually_exclusive_group(required=True)
    action.add_argument(
        "--validate",
        action="store_true",
        help="Validate the manifest without connecting to SITL",
    )
    action.add_argument(
        "--list",
        action="store_true",
        help="List validated scenario identifiers",
    )
    action.add_argument(
        "--scenario",
        help="Plan or execute one validated scenario",
    )
    parser.add_argument(
        "--execute",
        action="store_true",
        help="Actually inject parameters into a verified SITL connection",
    )
    parser.add_argument(
        "--connect",
        default="tcp:127.0.0.1:5760",
        help="MAVLink connection string for an existing SITL instance",
    )
    parser.add_argument(
        "--output-dir",
        default="data/sitl_runs",
        help="Directory for JSON run records",
    )
    parser.add_argument(
        "--log-path",
        help=(
            "Optional .BIN produced by SITL. It is hashed and referenced, "
            "never generated by this command."
        ),
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = _parser().parse_args(argv)
    scenarios = load_scenarios(args.manifest)

    if args.validate:
        print(
            f"Validated {len(scenarios)} SITL scenarios from "
            f"{Path(args.manifest)}"
        )
        return 0

    if args.list:
        for scenario in scenarios.values():
            labels = ", ".join(scenario.expected_diagnoses) or "control"
            print(f"{scenario.id}: {scenario.description} [{labels}]")
        return 0

    scenario = scenarios.get(args.scenario)
    if scenario is None:
        available = ", ".join(sorted(scenarios))
        raise SystemExit(
            f"Unknown scenario {args.scenario!r}. Available: {available}"
        )

    if not args.execute:
        print(json.dumps(asdict(scenario), indent=2))
        print(
            "\nPlan only. Add --execute after launching and arming an "
            "ArduPilot SITL vehicle in a stable hover."
        )
        return 0

    transport = MavlinkSITLTransport(args.connect)
    try:
        record = SITLScenarioRunner(transport).run(
            scenario,
            args.output_dir,
            log_path=args.log_path,
        )
    finally:
        transport.close()
    print(json.dumps(record, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
