from . import acceptance, analyze, baseline, batch, benchmark, capabilities, catalogue, checks, collect_forum, compare, demo, export, features, fleet, hardware, import_clean, label, log_finder, maintenance, methodic, mine_expert_labels, mission, param_diff, param_validate, params, report, ui, live, temporal, video

COMMAND_MODULES = [
    acceptance,
    analyze,
    baseline,
    capabilities,
    catalogue,
    log_finder,
    checks,
    export,
    hardware,
    param_diff,
    param_validate,
    params,
    report,
    features,
    fleet,
    benchmark,
    batch,
    compare,
    label,
    maintenance,
    methodic,
    mission,
    demo,
    import_clean,
    collect_forum,
    mine_expert_labels,
    ui,
    live,
    temporal,
    video,
]
